name: Deploy

on:
  workflow_dispatch:  # فقط اجرای دستی از طریق GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run deployment script
        run: echo "Deploying your project manually..."

